#!/bin/bash

# Configures git with the correct global settings...
# Useful on fresh installations of a new OS.
# Provide your name and email address that will be used IN QUOTES.

if [[ -z $1 ]] || [[ -z $2 ]]; then
  echo "Please specify a username and email address (in quotes)."
  exit
fi

editor="vim"
name="$1"
email="$2"

git config --global color.ui auto
git config --global core.editor "$editor"
git config --global user.name "$name"
git config --global user.email "$email"
git config --global core.excludesfile `pwd`/gitignore_global
